version: "3.2"

services:

        nucleus-arm:
                container_name: nucleus-arm
                image: elementaryrobotics/nucleus:aarch64
                volumes:
                        - type: volume
                          source: shared
                          target: /shared
                          volume:
                                  nocopy: true

        picamera:
                container_name: picamera
                build:
                        context: .
                        args:
                                opt_libs: "/opt/vc/lib"
                        dockerfile: Dockerfile
                volumes:
                        - type: volume
                          source: shared
                          target: /shared
                          volume:
                                nocopy: true          
                        - "/opt/vc:/opt/vc"
                devices:
                        - "/dev/vchiq:/dev/vchiq"
                        - "/dev/video0:/dev/video0"
                privileged: true
                depends_on:
                        - "nucleus-arm"


        streamviewer:
                container_name: stream-viewer
                image: elementaryrobotics/element-stream-viewer:test-aarch64
                volumes:
                        - type: volume
                          source: shared
                          target: /shared
                          volume:
                                nocopy: true
                        - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
                environment:
                        - "DISPLAY"
                        - "QT_X11_NO_MITSHM=1"
                depends_on:
                        - "nucleus-arm"
volumes:
        shared:
                driver_opts:
                        type: tmpfs
                        device: tmpfs

