version: "3.2"

services:

        nucleus-arm:
                container_name: nucleus-arm
                image: elementaryrobotics/nucleus:aarch64
                volumes:
                        - type: volume
                          source: shared
                          target: /shared
                          volume:
                                  nocopy: true

        picamera:
                container_name: test_cont
                build:
                        context: .
                        dockerfile: Dockerfile
                environment:
                        - LD_LIBRARY_PATH

                volumes:
                        - type: volume
                          source: shared
                          target: /shared
                          volume:
                                  nocopy: true          
                        - ".:/code"
                devices:
                        - "/dev/vchiq:/dev/vchiq"
                        - "/dev/video0:/dev/video0"
                privileged: true
                depends_on:
                        - "nucleus-arm"

volumes:
        shared:
                driver_opts:
                        type: tmpfs
                        device: tmpfs

